### ISSUE TITLE
在手机端访问有时会出现 Welcome to nginx 提示

### ISSUE THREAD

**Issue by shinexoh** [xingpingcn/enhanced-FaaS-in-China#10]
我的域名托管在 cf 上，把网站部署在 vercel，将 cname 记录写为`vercel-cname.xingpingcn.top`后不开小黄云，我也先把记录写成 vercel 官方的生成证书后才改为优选的。在手机端不开梯子有时访问会出现图中内容，但在电脑端访问就没遇到过。

![image](https://github.com/user-attachments/assets/8bb7bcb7-7367-464f-ab12-fa87a87c4776)

这是因为域名托管在 cf 然后 cname 使用优选导致的 403 吗？

**Comment by xingpingcn** [comment]
有两种可能

1. 节点每40分钟更新一次，可能在检测这个节点之前，这个节点出问题了
1. 可能在检测这个节点之后，vercel-cname.xingpingcn.top 已经剔除了这个出问题的节点，但是你的运营商dns有缓存，你获取的还是旧的有问题的节点的 A 记录

持续观察一段时间吧
