### ISSUE TITLE
报错 `Error 1034` 疑似分配到了，无权使用的 `IP` 段

### ISSUE THREAD

**Issue by dishao123** [xingpingcn/enhanced-FaaS-in-China#12]
![Edge-IP-Restricted-Cloudflare-12-15-2024_03_31_PM](https://github.com/user-attachments/assets/57b3093d-229e-4fb9-959b-02ecb7e06bdc)

之前还好好的，刚刚就这样了

**Comment by xingpingcn** [comment]
1. 我的无法复现
2. 你的网站403，建议把域名托管到非cf平台

**Comment by xingpingcn** [comment]
先关了，有问题随时再开
