### ISSUE TITLE
如果想要使用其他DNS路线解析服务，是否就没办法自动同步地址

### ISSUE THREAD

**Issue by GSYCCN** [xingpingcn/enhanced-FaaS-in-China#2]
Q：为什么分路线解析不准确？
A：我使用的是权威DNS服务器自带的路线解析，可能存在误判。如果你想要更加精准的分路线解析，可以自行选取其他DNS服务器——如dnspod——并添加[Netlify.json](https://raw.githubusercontent.com/xingpingcn/enhanced-FaaS-in-China/main/Netlify.json)或[Vercel.json](https://raw.githubusercontent.com/xingpingcn/enhanced-FaaS-in-China/main/Vercel.json)里的IP到A记录。

如上，添加A记录的时候，只能添加固定IP到A记录；但是Vercel.json里指示的IP似乎是动态更新的，如果没能及时将IP到A记录更新到最新Vercel.json中指示的IP，这是否会导致解析效果不好？

不是很了解DNS相关知识，望解答，谢谢。

**Comment by xingpingcn** [comment]
> 但是Vercel.json里指示的IP似乎是动态更新的
是动态更新的
> 如果没能及时将IP到A记录更新到最新Vercel.json中指示的IP，这是否会导致解析效果不好？
是的，所以我的建议是用cf worker等工具通过编码的方式每小时同步更新到你的dns服务器

目前来说，只有小部分地区分流不太准确
