### ISSUE TITLE
Vercel 优选无法应用于区域顶级上

### ISSUE THREAD

**Issue by gz4zzxc** [xingpingcn/enhanced-FaaS-in-China#9]
我自己的博客使用 Vercel 部署，使用 `example.com`作为主页，域名的 DNS 托管在 cloudflare 上。

使用本项目将原本 `example.com` 从 A 记录 `76.76.21.21` 改成使用本项目中的 cname `vercel-cname.xingpingcn.top`（此时 cloudflare 提示`CNAME 记录通常不能位于区域顶级。我们使用 CNAME 拉平达到此目的`），加速似乎不生效，使用 ITdog 网站 DNS 查询解析国内国外均为 `76.76.21.21`，没有优选到优选 ip 上。

![CleanShot 2024-09-27 at 21 08 12](https://github.com/user-attachments/assets/1ebbf255-d8b5-4de7-a652-78144db4f62f)

同域名子域名`*.example.com` cname 改为`vercel-cname.xingpingcn.top`，则无以上问题，能实现中国加速。

请问 vercel 中是否只能在子域名`*.example.com`使用本项目？

**Comment by xingpingcn** [comment]
按照标准，顶级域名是不能添加 cname 记录的。cf 的 [CNAME flattening](https://developers.cloudflare.com/dns/cname-flattening/)[CNAME flattening](https://developers.cloudflare.com/dns/cname-flattening/) 事实上是 cf 在 **国外** 的服务器帮你做 a 记录解析，然后给你（客户端）返回 **这些**  ip 的。因而使用本项目的c name 返回的都是国外的 ip。

P.S. 如果你用过 NS1.COM 作为 dns 服务器，其独有的 alias 记录也是同样的道理。

其他的 dns 服务器就是支持在顶级域名添加 cname 记录的，例如 dnspod，华为 dns等。你可以把域名托管在这些 dns 服务器。

**Comment by gz4zzxc** [comment]
谢谢大佬解答🙏
